<EMOTION> <EXP_DESCRIPTION>:
  - Please describe the speaking style, content, and the speaker's emotional state of this speech.
  - Please describe the speaking style, content, and the speaker's emotional state of this speech.
  - Please describe the speaking style, content, and the speaker's emotional state of this speech.
  - Please describe the speaking style, content, and the speaker's emotional state of this speech.
  - Please describe the speaking style, content, and the speaker's emotional state of this speech.
<EMOTION> <IMP_DESCRIPTION>:
  - Please consider the speaking style, content, and directly provide the speaker's emotion in this speech.
  - Please consider the speaking style, content, and directly provide the speaker's emotion in this speech.
  - Please consider the speaking style, content, and directly provide the speaker's emotion in this speech.
  - Please consider the speaking style, content, and directly provide the speaker's emotion in this speech.
  - Please consider the speaking style, content, and directly provide the speaker's emotion in this speech.
